# --request ~ -X
# --header ~ -H
# --data ~ -D

### GET request ###
curl -X GET  http://localhost:3000/

### POST request ###
curl --request POST http://localhost:3000/post 
   --header 'Content-Type: application/json'
   --data  '{
    "login": "sergey",
    "password": "password"
        }'

